sudo: false
git:
    submodules: false

language: shell # We do everything inside Docker

services:
  - docker

env:
  global:
   - BUILD_DIR=/opt/src/github.com/archzfs/archzfs
   - DOCKER_BASE=base/devel
  matrix:
   - KERNEL=std
   - KERNEL=lts
   - KERNEL=hardened
   - KERNEL=zen
   - KERNEL=dkms

before_install:
 # upgrade docker
 - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
 - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
 - sudo apt-get update
 - sudo apt-get -y install docker-ce
 # use http for submodules
 - sed -i 's/ssh+git:\/\/aur@aur.archlinux.org/https:\/\/aur.archlinux.org/' .gitmodules
 - git submodule update --remote
 # pull lastest image
 - docker pull ${DOCKER_BASE}

install:
 # run container
 - docker run -d --privileged --cidfile=/tmp/cidfile -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v ${PWD}:${BUILD_DIR} ${DOCKER_BASE} /sbin/init
   
 # exec install script
 - docker exec `cat /tmp/cidfile` /bin/bash ${BUILD_DIR}/ci/install.sh

script:
 # build packages  
 - docker exec --user demizer `cat /tmp/cidfile` /bin/bash ${BUILD_DIR}/ci/build.sh ${KERNEL}

 
after_script:
 - docker kill `cat /tmp/cidfile`
